spring:
  application:
    name: Tortoise
  datasource:
    url: jdbc:h2:file:./data/tortoise-db
    username: admin
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
  h2:
    console:
      enabled: true