CREATE TABLE AppUser(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE UserRole(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE User_UserRole(
    user_ID BIGINT,
    user_Role_ID BIGINT,
    PRIMARY KEY (user_ID, user_Role_ID),
    FOREIGN KEY (user_ID) REFERENCES AppUser(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (user_Role_ID) REFERENCES UserRole(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);